Wdp 116
gonczor/presence-analyzer-wgonczaronek pull request #2
Opened 2017-04-06 10:29 UTC by gonczor

Added tests, updated .gitignore for coverage files, updated requirements.txt

2017-04-06 10:30 UTC, gonczor commented
![image](https://cloud.githubusercontent.com/assets/10250139/24749816/d18d4e58-1ac4-11e7-95cf-e5bda9391b4e.png)

2017-04-06 10:46 UTC, gonczor commented
![image](https://cloud.githubusercontent.com/assets/10250139/24750703/17e8784e-1ac7-11e7-9ae1-a2e4a90844ce.png)

2017-04-06 18:41 UTC, dpolcyn commented on runtime/data/test_data_with_header_and_footer.csv
> +header
please explain me this 'header' thing, also why did you created new file with test data?

2017-04-06 18:42 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +    def test_presence_weekday_wrong_id(self):
wrong id? what is wrong with 1?

2017-04-06 18:43 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +        Test data contains ids: 10 and 11. Giving number -1 should result in 404 exit code
-1? why not just id of user that doesn't exist?

2017-04-06 18:45 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +        From test_data.csv:
In which standard doc did you wrote this? Link please

2017-04-06 18:45 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +        self.assertEqual(response.status_code, 200)
Empty line after this line

2017-04-06 18:45 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +        # Change to dict for easier checks
check json loads format

2017-04-06 18:46 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +        self.assertEqual(data[u'Weekday'], u'Presence (s)')
from __future__ import unicode_literals

2017-04-06 18:47 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +        self.assertEqual(data[u'Tue'], 30047)
If you gona check for example year, then you gona check every day too? it should be just dict check or list check, you don't have to check all position one by one

2017-04-06 18:47 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +        self.assertEqual(data[u'Mon'], 0)
ditto

2017-04-06 18:47 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +        data = dict(data)
ditto

2017-04-06 18:48 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +        self.assertEqual(len(data), 7)
if you check whole dict then you don't have to check length

2017-04-06 18:51 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +        self.assertEqual(utils.seconds_since_midnight(midnight_time), 0)
don't assign variable if u want to use it once

2017-04-06 18:51 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +        Test interval
more information, full stop on the end of docstring

2017-04-07 05:32 UTC, piotrgrundas requested changes

2017-04-07 05:32 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +        self.assertAlmostEqual(utils.mean(items), 1.5, 3)
Do both in one test, dont assign var if ur using it only once.

2017-04-07 05:32 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +        # Ensure it contains 1 hour interval
Imo ur overusing comments.
Compare whole dict instead of all this?

2017-04-07 05:32 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +                                       'Problem with line' in x.msg, log_capture.records)))
I don't like this + wrong styles. If u rly wanted to test it u should use mock like:
![image](https://cloud.githubusercontent.com/assets/5078402/24786736/1b82e94c-1b64-11e7-9da3-a900f71f4272.png)

2017-04-07 05:32 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +            main.app.config.update({'DATA_CSV': TEST_DATA_CSV})
This is not needed. Check what `setUp` func does

2017-04-07 08:34 UTC, gonczor commented on runtime/data/test_data_with_header_and_footer.csv
> +header
If there is a different number of fields than 4, get_data() skips it. The comment said it was for checking for headers and footers, so I've added a file with data for testing this piece of code. I didn't want to mess with test_data.csv

2017-04-07 08:35 UTC, gonczor commented on src/presence_analyzer/tests.py
> +    def test_presence_weekday_wrong_id(self):
It's not in test_data.csv, so the user doesn't exist. I guess I should make this more descriptive?

2017-04-07 08:35 UTC, gonczor commented on src/presence_analyzer/tests.py
> +        Test data contains ids: 10 and 11. Giving number -1 should result in 404 exit code
Done.

2017-04-07 08:36 UTC, gonczor commented on src/presence_analyzer/tests.py
> +        self.assertEqual(response.status_code, 200)
Done

2017-04-07 08:38 UTC, gonczor commented on src/presence_analyzer/tests.py
> +        self.assertEqual(data[u'Weekday'], u'Presence (s)')
Done

2017-04-07 08:40 UTC, gonczor commented on src/presence_analyzer/tests.py
> +        self.assertEqual(utils.seconds_since_midnight(midnight_time), 0)
Done

2017-04-07 08:42 UTC, gonczor commented on src/presence_analyzer/tests.py
> +        Test interval
Done

2017-04-07 08:43 UTC, gonczor commented on src/presence_analyzer/tests.py
> +        self.assertAlmostEqual(utils.mean(items), 1.5, 3)
Done

2017-04-07 08:44 UTC, gonczor commented on src/presence_analyzer/tests.py
> +            main.app.config.update({'DATA_CSV': TEST_DATA_CSV})
Done

2017-04-07 08:45 UTC, gonczor commented on src/presence_analyzer/tests.py
> +                                       'Problem with line' in x.msg, log_capture.records)))
I couldn't get mock.patch to work as I wanted. I can check contents of log_capture instead.

2017-04-07 08:48 UTC, gonczor commented on src/presence_analyzer/tests.py
> +        # Ensure it contains 1 hour interval
Yep, cleared.

2017-04-07 08:59 UTC, gonczor commented on src/presence_analyzer/tests.py
> +        From test_data.csv:
Corrected

2017-04-07 17:48 UTC, gonczor commented on src/presence_analyzer/tests.py
> +        self.assertEqual(len(data), 7)
Done

2017-04-07 18:01 UTC, gonczor commented on src/presence_analyzer/tests.py
> +        self.assertEqual(data[u'Tue'], 30047)
Done

2017-04-10 10:55 UTC, piotrgrundas requested changes

2017-04-10 10:55 UTC, piotrgrundas commented on src/presence_analyzer/utils.py
> +                # logging.debug('Sample msg')
?

2017-04-10 10:55 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +        data = utils.group_by_weekday(data)
vars

    post/some work etc

    asserts

2017-04-10 10:55 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +        self.assertAlmostEqual(utils.mean([1, 2]), 1.5, 3)
`test_mean_with_empty_list` and `test_mean_with_non_empty_list` in one test
Couple more cases.

2017-04-10 10:55 UTC, piotrgrundas commented on runtime/data/test_data_with_header_and_footer.csv
> +header
You won't have headers like that, in csv in 99% cases num of header cols will match data num cols.

2017-04-10 10:55 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +from mock import patch
sort imports + group them
https://www.python.org/dev/peps/pep-0008/#imports

2017-04-10 10:55 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +            ]
wrong indent - untab once

2017-04-10 10:55 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +            ]
ditto

2017-04-10 10:55 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +        self.assertEqual(utils.interval(datetime.time(0, 0, 0), datetime.time(1, 1, 1)), 3661)
Couple more cases.

2017-04-10 10:55 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +
![image](https://cloud.githubusercontent.com/assets/5078402/24858523/f60da004-1dec-11e7-8956-f6f35b51a6c8.png)

2017-04-10 11:00 UTC, piotrgrundas requested changes

2017-04-10 11:00 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +        :param mocked_log: mocked logger.
IMO adding :param to tests is pointless.

2017-04-10 11:06 UTC, gonczor commented on src/presence_analyzer/utils.py
> +                # logging.debug('Sample msg')
Sorry, I forgot to delete it after testing logging mock.

2017-04-10 11:43 UTC, piotrgrundas requested changes

2017-04-10 11:43 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +            ]
expected_data = [
        [calendar.day_abbr[weekday], utils.mean(intervals)]
        for weekday, intervals in enumerate(weekdays)
    ]

2017-04-10 11:56 UTC, piotrgrundas approved these changes

2017-04-10 11:57 UTC, merged